"""create excluded name table

Revision ID: 162aac1db30e
Revises: 4f043fafa0ec
Create Date: 2026-09-29 21:45:38.698069

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '162aac1db30e'
down_revision = '4f043fafa0ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('excluded_name',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###

    # Seed a default exclusion - remove it from /config if you don't want it.
    excluded_name = sa.table('excluded_name', sa.column('name', sa.String()))
    op.bulk_insert(excluded_name, [{'name': 'Mel'}])


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('excluded_name')
    # ### end Alembic commands ###
