"""create journal entry table

Revision ID: 255f1e116912
Revises: 
Create Date: 2021-01-13 16:57:21.884820

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '255f1e116912'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('journal_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entry_text', sa.String(), nullable=True),
    sa.Column('timestamp', sa.Integer(), nullable=True),
    sa.Column('entry_date', sa.Date(), nullable=True),
    sa.Column('names', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('word_count', sa.Integer(), nullable=True),
    sa.Column('sentence_count', sa.Integer(), nullable=True),
    sa.Column('paragraph_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_journal_entry_entry_date'), 'journal_entry', ['entry_date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_journal_entry_entry_date'), table_name='journal_entry')
    op.drop_table('journal_entry')
    # ### end Alembic commands ###
