"""add analyzed_at to journal_entry

Revision ID: 2aab6e720291
Revises: 162aac1db30e
Create Date: 2026-09-30 14:25:34.038111

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2aab6e720291'
down_revision = '162aac1db30e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('journal_entry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('analyzed_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('journal_entry', schema=None) as batch_op:
        batch_op.drop_column('analyzed_at')

    # ### end Alembic commands ###
