"""add locations, daily score, and journal photo

Revision ID: 4ca04575c2a8
Revises: fae2e57c7ca2
Create Date: 2026-09-29 14:22:27.951139

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ca04575c2a8'
down_revision = 'fae2e57c7ca2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('journal_photo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('journal_entry_id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('caption', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['journal_entry_id'], ['journal_entry.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('journal_photo', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_journal_photo_journal_entry_id'), ['journal_entry_id'], unique=False)

    with op.batch_alter_table('journal_entry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('locations', sa.ARRAY(sa.String()), nullable=True))
        batch_op.add_column(sa.Column('daily_score', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('journal_entry', schema=None) as batch_op:
        batch_op.drop_column('daily_score')
        batch_op.drop_column('locations')

    with op.batch_alter_table('journal_photo', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_journal_photo_journal_entry_id'))

    op.drop_table('journal_photo')
    # ### end Alembic commands ###
